name = "welovemusicals"
compatibility_date = "2026-04-04"

[build]
command = "pnpm run build"
cwd = "."

[assets]
directory = "dist/public"
binding = "ASSETS"

[env.production]
routes = [
  { pattern = "welovemusicals.com/*", zone_name = "welovemusicals.com" }
]

[observability]
enabled = true
